export const NUMBER_PRESSED = "NUMBER_PRESSED";
export const CLEAR_PRESSED = "CLEAR_PRESSED";
export const BACKSPACE_PRESSED = "BACKSPACE_PRESSED";
export const DECIMAL_PRESSED = "DECIMAL_PRESSED";
export const ENTER_PRESSED = "ENTER_PRESSED";
export const BINARY_OPERATOR_PRESSED = "BINARY_OPERATOR_PRESSED";